# K8s based s3 server master details.
# Note: Make sure master/worker credentials are same as we are using them to collect system stat.
"nodes":
    - "hostname": ""
      "username": ""
      "password": ""
      "node_type": "master"
"restapi":
  "ip": ""
  "port": ""
  "username": ""
  "password": ""
